### ISSUE TITLE
`@yext/pages init` doesn't tell you to `cd`

### ISSUE THREAD

**Issue by Mxs2019** [yext/pages#137]
### Describe the bug

If you the run the command `npx @yext/pages init <my-site-name>` a new site is created. The directions say
```
Done! Try following commands to start:
npm run dev   # Start a development server
```

However this won't work unless you first change into the right directory. It would be more clear to have something like 
```
Done! Try following commands to start:
cd <my-site-name>
npm run dev   # Start a development server
```

### System Info

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Memory: 111.73 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Safari: 15.1
  npmPackages:
    @yext/pages: 1.0.0-beta.0 => 1.0.0-beta.0
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
closed with https://github.com/yext/pages/pull/149
