### ISSUE TITLE
Stream Types Codegen

### ISSUE THREAD

**Issue by Mxs2019** [yext/pages#139]
### Description

As a developer I want to full use the power of typescript to prevent any errors at build time and have rich autocomplete. The main gap right now is that entities that are streamed from the knowledge graph. You have to completely write the types from scratch and then cast the props as a type in order to get typescript work. 

### Suggested solution

It would be super helpful to have a command like `yext types generate` that would automatically generate the types for any streams used by templates as well as global streams. There would then be a way to to inject those. Somethign like...
```
import { DentistTemplateProps } from ./types
...

export const getPath: GetPath<DentistTemplateProps>
...
export const getHeadConfig: GetHeadConfig<DentistTemplateProps> = 
...
Template<DentistTemplateProps> = 
```

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
The bulk of that work would be outside the scope of this library since it would live in the Yext CLI. Once support is added there then we can hook it up here to work with your template configs.

**Comment by mkilpatrick** [comment]
This has been completed.
