### ISSUE TITLE
Global Component Wrapper

### ISSUE THREAD

**Issue by Mxs2019** [yext/pages#140]
### Description

From time to time you want to add a global component wrapper across ALL templates. This could be something UI related or could be something like an analytics provider or a bug reporting provider. 

Today the only way to do that is to manually add it to each individual template and wrap each template in shared code. You can abstract this into a `<Layout>` component but that is still tedious and error prone. 

Next.js has `app.js` and a `document.js` for exactly this reason. Something similar would be helpful. 

### Suggested solution

Do something similar to `next.js` with their `app.js` and `document.js`. Remix has an `entry.client.js` which is kinda similar as well. https://remix.run/docs/en/v1/api/conventions#entryclienttsx. 

I'd propose an `app.js` file that lives in the `src` repo. It allows you add global components that wrap around every template. Under the hood it would do the exact same thing as individually wrapping each page. So something like where `<Wrapper>` is a custom component

```
function MyApp({ Component, pageProps }) {
  return <Wrapper><Component {...pageProps} /></Wrapper>
}

export default MyApp
```

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Consulting has added an `AnalyticsProvider` wrapper. If we were to add the concept of a layout, it would no longer live in this repo. Maybe `@yext/react-components`.

**Comment by Ceseura** [comment]
Are there any updates on this? I think a template like this would be quite helpful for implementing i18n support, as well as for adding a Custom Field usage highlighter, and other things that require interacting with the entire page from the top-most level component. Our current implementations involve pasting the same component into each template file `index.tsx` `directory.tsx` etc which just wraps the normal exported template. Adding this feature could remove a lot of replicated code.

**Comment by mkilpatrick** [comment]
We actually have support for a single global _client.tsx and _server.tsx (in src/templates) that gives you full React rendering control. There's no documentation on it yet, but here's an example. Just note that it's global for **every** template.

```
_client.tsx

// Environment: browser

import * as ReactDOM from "react-dom";
import * as React from "react";
import { PageContext } from "@yext/pages";

export { render };

const render = async (pageContext: PageContext<any>) => {
  const { Page, pageProps } = pageContext;
  ReactDOM.hydrate(
    <Page {...pageProps} />,
    document.getElementById("reactele"),
  );
};
```

```
_server.tsx

// Environment: server

import * as ReactDOMServer from "react-dom/server";
import * as React from "react";
import { PageContext } from "../types.js";

export { render };

const render = async (pageContext: PageContext<any>) => {
  const { Page, pageProps } = pageContext;
  const viewHtml = ReactDOMServer.renderToString(<Page {...pageProps} />);

  return `<!DOCTYPE html>
    <html lang="<!--app-lang-->">
      <head></head>
      <body>
        <div id="reactele">${viewHtml}</div>
      </body>
    </html>`;
};
```

Another option is to create your own layout wrapper than you call in each template, but sounds like you're looking to avoid this.

```
/src/layouts/foo.tsx

export const Foo = (children) => {
  return <Somei18nThing>{children}</Somei18nThing>
}
```

```
src/templates/location.tsx

const Location: Template<TemplateRenderProps> = ({
  relativePrefixToRoot,
  document,
}) => {
  ...
  return <Foo>.....</Foo>
```

**Comment by mkilpatrick** [comment]
Closing this out as not scheduling. If it comes up again we will reassess.
