### ISSUE TITLE
Redirect urls with trailing slashes in dev server 

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#143]
### Description

Currently it's possible to visit urls with or without a trailing slash. For example an entity page can be accessed at both `http://localhost:5173/location/123` and `http://localhost:5173/location/123/`.

This is confusing because of how it interacts with the `relativePrefixToRoot`. A link like: ```<a href={`${relativePrefixToRoot}path`}>Link</a>``` 
will take you to `http://localhost:5173/location/path` if you're viewing the page with a trailing slash in the url and `http://localhost:5173/path` if you're viewing the page without a trailing slash. 

 

### Suggested solution

Redirect urls with trailing slashes in the dev server to a version without the trailing slash. That would make it closer to how it operates in production. 

### Alternative

The logic used to calculate `relativePrefixToRoot` could just ignore the trailing slash, but seems nicer to remove entirely. 

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
closed with https://github.com/yext/pages/pull/148
