### ISSUE TITLE
Show File Size Limit in Local Dev

### ISSUE THREAD

**Issue by Mxs2019** [yext/pages#145]
### Describe the bug

There is a `1mb` file size limit in the function system that generates pages. This limit spits out an error like
```
Error encountered in site configuration: source file assets/server/locator.6a26f199.js for plugin Generator-ry2nmj5shd exceeds max size of 1 MB
```

This error should be caught in local development and should throw an error. It would also be helpful if the error message was more helpful and pointed out how to fix the error. 

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 538.21 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 88.0.1
    Safari: 15.6
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Closed with https://github.com/yext/pages/pull/147
