### ISSUE TITLE
Broken Example Links

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#166]
### Describe the bug

I'm running `npm run dev`. On the homepage I see some example links for my features 
![image](https://user-images.githubusercontent.com/6308571/184924458-8a18d72b-5487-4148-9d55-865ae6228381.png)

When I click the example location link I get taken to a page that returns a 500:
![image](https://user-images.githubusercontent.com/6308571/184924557-ee1a1f53-0aa0-4984-b5b6-814522b5cd96.png)

I think this is probably because the example links come from localData, but I'm not `yext init`ed with the same account that was used to generate test data. 

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.86 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.1 => 1.0.0-beta.1
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Hmm, idk if there's a good way to prevent that. If you have the localData and use `npm run dev -- local` it would work fine. The library can't know if you've not init'ed against the correct account or not.

**Comment by nbramblett** [comment]
The actual entity data is fetched live when running dev without local, perhaps we could do the same for the index page (aka dynamically fetch a set of entities for the index)?

Is it possible to use the CLI to, say, query `fetch list of all entity ids for type X`?

**Comment by bhainesva** [comment]
Is this only happening because the `generate-test-data` call failed? 

Would it make sense to hide the sample links in that case with a message about why? Or maybe check if the businessId in the existing localData matches the account we were trying to generate test data from?

**Comment by mkilpatrick** [comment]
The index just dumps out the localData you have. I don't think pagesjs should try to inspect the init state of the CLI to assume what you're trying to do, assuming that's even possible (there might be a .yext file we could get this from).

GTD (going to use this acronym as shorthand) is run on server start to initially get the localData to show on the index. It sounds like it failed for you and then just used what was leftover from another GTD. We could probably kill the server or something so it's clearer? Not entirely sure what would be best. I've seen GTD fail many times, even for single pages when you make rapid requests.

**Comment by bryanreed** [comment]
I'm definitely for hiding example links from localData if we didn't run the command in local mode.  In dynamic mode it can run GTD under the hood if we want (but ideally not write the actual files) to generate some links for the page.

**Comment by mkilpatrick** [comment]
Nothing to do here at this point.
