### ISSUE TITLE
Dev server crashes when visiting url without entityId

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#168]
### Describe the bug

I'm serving a site with a `job` template. If I visit a url like `http://localhost:5173/job/<valid-id>` the page renders as expected. If I visit a url like `http://localhost:5173/job/<invalid-id>` I get a 500, also as expected. 

If I visit `http://localhost:5173/job` the dev server crashes with this error:
```
Generated 10 files for stream "job-stream"/Users/bhaines/repo/<REPONAME>/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

SyntaxError: Unexpected token { in JSON at position 485
    at JSON.parse (<anonymous>)
    at ChildProcess.<anonymous> (file:///Users/bhaines/repo/<REPONAME>/node_modules/@yext/pages/dist/dev/server/ssr/generateTestData.js:85:25)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:520:28)
    at Pipe.<anonymous> (node:net:687:12)

Node.js v17.4.0
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.76 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.1 => 1.0.0-beta.1
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by nbramblett** [comment]
I was able to diagnose this issue - when the dev server is set up to run `generate-test-data` dynamically, it will specify an entity iff you pass an entity id in the url. If you don't pass one (as in the reported case), the generated test data will concatenate multiple json objects together, like
```
{
  ...
}
{
  ...
}
```
which the parser cannot handle.

I think there are two separate steps to remediation here - first is handle the case of unspecified IDs better, and second is to more generally catch these errors and gracefully reroute to a 500 page or something similar.
