### ISSUE TITLE
yarn build fails when features.json has a syntax error

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#181]
### Describe the bug

To reproduce: 
1. Introduce a syntax error into your features.json file, for example by removing a comma in the field list for a stream definition. 
2. run `yarn build`

This gives an error like:
```
✖ [1ms] Failed to write /Users/bhaines/repo/site-starter-react-basic/sites-config
Unexpected string in JSON at position 1797
```

This is confusing because there's nothing wrong with my actual templates. I believe the `features.json` is just being overwritten, so I don't think its current state should really matter. 

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.25 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.1 => 1.0.0-beta.1
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
The features.json is currently merged into rather than completely overwritten since we don't currently have a way to support global features settings. Once we do we can overwrite completely.

**Comment by mkilpatrick** [comment]
With consolidated configs are complete this will no longer be an issue.
