### ISSUE TITLE
`pages generate features` fails with css/ts errors, `yarn build` succeeds

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#183]
### Describe the bug

I'm upgrading this repo: https://github.com/yextconsulting/site-starter-react-consulting to 1.0.0-beta.2. 

After doing that, running `pages generate features` fails and lists warnings/errors related to CSS / tsx. 
![image](https://user-images.githubusercontent.com/6308571/186526781-79baf802-f85b-43e8-a189-26537a2edfc9.png)

`yarn build` and `yarn dev` both succeed without any warnings. In general I don't think this command should fail when that's the case. 

Some of the specific things it's complaining about here also shouldn't be warnings at all. The CSS syntax for example technically isn't correct CSS, but it's valid with the postcss plugins we're using and there's nothing to fix about it. 

### Reproduction

https://github.com/yextconsulting/site-starter-react-consulting 

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 470.23 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.2 => 1.0.0-beta.2
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [x] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Is this still an issue with 1.0.0-beta.4?

**Comment by bhainesva** [comment]
yes

**Comment by mancusi** [comment]
This is due to the fact that `pages generate features`  uses `esbuild` to transpile modules on the fly whereas `pages dev` and `pages build` received modules which have already been transpiled by vite.

@mkilpatrick I think we'll want to rethink how we're importing modules here and potentially introduce vite into this rather than relying directly on esbuild.

**Comment by mkilpatrick** [comment]
Loader issues have been addressed in https://github.com/yext/pages/pull/331
