### ISSUE TITLE
useTrack hook throwing ReferenceError: window is not defined

### ISSUE THREAD

**Issue by lambdaFun94** [yext/pages#185]
### Describe the bug

When using useTrack in a button component, I am getting a 500 error: 500 ReferenceError: window is not defined
at useAnalytics (file:///Users/asanchez/product/analytics-docs/node_modules/@yext/pages/dist/components/analytics/hooks.js:12:3)

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Max
    Memory: 25.98 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.6.0 - ~/.nvm/versions/node/v18.6.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v18.6.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Safari: 15.4
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Fixed by https://github.com/yext/pages/pull/186
