### ISSUE TITLE
image component doesn't work with sandbox images

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#191]
### Describe the bug

I'm trying to use the Image component to render an image field from my sandbox account. 

The url of the image returned in the page stream is: https://a.mktgcdn.com/p-sandbox/VYBcb-dDm5a6O0Ia-88tDeBny-mm7Hpd6PWBar9HgAg/1057x705.jpg.

When I pass this to the Image component the url gets turned into:  https://dynl.mktgcdn.com/p/VYBcb-dDm5a6O0Ia-88tDeBny-mm7Hpd6PWBar9HgAg/500x500 (`p` instead of `p-sandbox`). 

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 372.65 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.2
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.4 => 1.0.0-beta.4
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by nbramblett** [comment]
Resolved by PR #192
