### ISSUE TITLE
AnalyticsProvider / AnalyticsScope Should Allow Entity Level Scoping

### ISSUE THREAD

**Issue by benmcginnis** [yext/pages#212]
### Description

For more-complex applications (like a Locator or Directory), we need to be able to track a click on a specific entity when there are multiple entities displayed on a given page.  

### Suggested solution

This is a little complex given the current design of the classes, but this could be an optional parameter on the AnalyticsScope component.  We'd have to investigate how to make this work with the current design of the Analytics class and the Analytics Provider. 

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Thanks for the feature request! We will include this in our rework of the `AnalyticsProvider`. This rework will happen as part of the Analytics Endpoints consolidation initiative.
