### ISSUE TITLE
alternateLanguageFields data not available in dynamic mode

### ISSUE THREAD

**Issue by tatimblin** [yext/pages#228]
### Describe the bug

I have added
```
alternateLanguageFields: [
  "slug",
],
```
to my stream and regenerated my features.json, following the steps outlined [here](https://www.notion.so/Advanced-Multi-Lang-Support-93db0ef3a01f4536ab6f5a4378b59561). Next I re-served my site and expected to be able to interact with the new data in the document object
```
"alternateLanguageFields": {
	"es_US": {
		"slug": "es_US/123-main-st"
	}
},
```

This data however was not available when serving in dynamic mode, I was able to serve with local data as expected though.

### Reproduction

https://github.com/yext-pages/Master-Ria/tree/dev/trunk checkout dev/trunk and then add the first code block to the stream

### System Info

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 177.05 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 18.4.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @yext/pages: 1.0.0-beta.6 => 1.0.0-beta.6
```

### Used Package Manager

pnpm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by Ceseura** [comment]
@tatimblin How were you able to serve with localData? When I run `yext sites generate-test-data` the generated JSON file also doesn't include the `alternateLanguageFields` data.

**Comment by tatimblin** [comment]
@Ceseura did you add this to your stream request?
```
alternateLanguageFields: [
  "c_customField",
],
```

**Comment by tatimblin** [comment]
I've added a screen recording going through the issue described here.

https://user-images.githubusercontent.com/13454298/195708925-5c69af94-c679-4a4a-b8b6-b35d67308d22.mov

Originally I posted that I was able to get this data in localData mode, but since wiping my localData I have been unable to reproduce that discrepancy.
