### ISSUE TITLE
Generic TemplateProps types

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#251]
### Description

I would like to type the entity data that's getting passed to my templates. Currently yext/pages hardcodes the type of the document as `Record<string, any>`. 

That means I either need to do an explicit cast like `const doc = data.document as LocationProfile` or create a custom version of TemplateProps like this: https://github.com/yextconsulting/site-starter-react-consulting/pull/105. It would be nice if that functionality was built in by making TemplateProps/TemplateRenderProps generic. 

### Suggested solution

Redefine `TemplateProps` as
```
export interface TemplateProps<T = Record<string, unknown>> {
  document: T;
  __meta: {
    mode: "development" | "production";
    manifest?: Manifest;
  };
}
```

and similar for `TemplateRenderProps`

### Alternative

https://github.com/yextconsulting/site-starter-react-consulting/pull/105

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
We will soon start work on a CLI command to generate TS types from a PagesJS-style repo. As part of this work, we will update `TemplateProps` to accept a Type param.

**Comment by mkilpatrick** [comment]
Completed in https://github.com/yext/pages/pull/332
