### ISSUE TITLE
Pure JS Rendering Broken in Local Dev

### ISSUE THREAD

**Issue by Mxs2019** [yext/pages#258]
### Describe the bug

I'm trying to use Pure JS rendering where you export a render function instead of the React Component. 

When doing local dev I get the following error:
```
Error: Default export missing in template
```

While the documentation makes it clear that local dev doesn't support hot module reloading I should be able to see the page. If this is not supported the error message should make it more clear. 

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 94.58 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 105.0.3
    Safari: 16.1
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tatimblin** [comment]
@Mxs2019 What version are you using? This was fixed in beta 7, but seems it could have resurfaced in 9.

https://github.com/yext/pages/issues/218
