### ISSUE TITLE
npm run dev- Yext CLI error - Windows 10

### ISSUE THREAD

**Issue by nobelanp** [yext/pages#263]
### Describe the bug

By using this manual https://hitchhikers.yext.com/tracks/pages-development/pgs601-build/03-create-site/ can't start project, on step "npm run dev". I have error:
/bin/bash: C:\Users\Username\Documents\testsite\test3\node_modules\.bin\..\@yext\pages\dist\bin\pages.sh: No such file or directory

### System Info

```shell
Windows 10 Pro 21H2
NodeJS v18.12.1
npm 8.19.2
Yext CLI Version: 0.1_304
deno 1.27.2 (release, x86_64-pc-windows-msvc)
v8 10.8.168.4
typescript 4.8.3
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Hi @nobelanp,

Thanks for bringing this issue to our attention! We have a couple follow up questions to help us investigate further. First, could you provide a link to the repository you're working with? Or one where the issue is recreated. Secondly, which terminal environment are you using? Cygwin, Power Shell, or Windows Terminal? 

Thanks very much,

Tom

**Comment by nobelanp** [comment]
Hello. 
Power shell in windows terminal.
Link to repo: [https://github.com/nobelanp/nobetest2]

**Comment by tmeyer2115** [comment]
Just confirming, if your run `npm install` in your repo, you don't see a `pages.sh` file at `C:\Users\Username\Documents\testsite\test3\node_modules.bin..https://github.com/yext\pages\dist\bin\pages.sh`?

**Comment by nobelanp** [comment]
I have this file. Looks like Windows folders routing issue (like slash and backslash). 
 pages.sh contain:
#!/usr/bin/env bash
/usr/bin/env node --experimental-specifier-resolution=node node_modules/@yext/pages/dist/bin/pages.js "$@"

**Comment by tmeyer2115** [comment]
Agreed, I think the proper path would be something like: 
```C:\Users\Username\Documents\testsite\test3\node_modules.bin\..`@yext\pages\dist\bin\pages.sh. ```
The `@` symbol likely needs to be escaped and it seems like a slash or two is missing. We're looking into the path construction now!

**Comment by tmeyer2115** [comment]
Hi @nobelanp! It seems as if NPM is responsible for generating the problematic path. When an NPM dependency has a `bin` in its `package.json`, NPM automatically creates a symlink for it in your `node_modules\.bin` folder. In your case, NPM generates a symlink at `node_modules\.bin\pages` that points to `C:\Users\Username\Documents\testsite\test3\node_modules.bin..@yext\pages\dist\bin\pages.sh`. Our current theory is that NPM is generating incorrect symlinks on Windows when the linked package (`@yext/pages`) has a special character in the name. We're still verifying this.

In the meantime, as a workaround, you can first delete the incorrectly generated symlink at `node_modules\.bin\pages`. Then, you can remake the symlink manually, but with the correct Windows path.

**Comment by nobelanp** [comment]
Pages file in .bin folder:
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/bash" ]; then
  exec "$basedir/bash"  "$basedir/../@yext/pages/dist/bin/pages.sh" "$@"
else 
  exec bash  "$basedir/../@yext/pages/dist/bin/pages.sh" "$@"
fi


```

 bash (usually should be node). Windows not have bash. 

> In the meantime, as a workaround, you can first delete the incorrectly generated symlink at node_modules\.bin\pages. Then, you can remake the symlink manually, but with the correct Windows  path.

Not helps

**Comment by tmeyer2115** [comment]
When generating the path in Windows, do you need to be escaping the `@` symbol?
