### ISSUE TITLE
npx @yext/pages init <my-site-name> command fails

### ISSUE THREAD

**Issue by vrunt** [yext/pages#265]
### Describe the bug

Following the guide process here: https://hitchhikers.yext.com/modules/pgs601-build/03-create-site/?target=using-npx

Fails with the following error:
```
node:internal/modules/cjs/loader:1029
  throw err;
  ^

Error: Cannot find module '/Users/nlamagna/Documents/Sites/node_modules/@yext/pages/dist/bin/pages.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1026:15)
    at Module._load (node:internal/modules/cjs/loader:872:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v19.1.0
```

![screenshot_2022-12-01_14-24-15](https://user-images.githubusercontent.com/5742690/205144618-d5c90469-7228-44de-91e4-e14fa08aea33.png)

### System Info

```shell
System:
    OS: macOS 11.6.8
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 45.00 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 19.1.0 - ~/.nvm/versions/node/v19.1.0/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v19.1.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 95.0.2
    Safari: 15.6.1
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tatimblin** [comment]
Hi @vrunt, what version of @yext/pages do you have installed? Newer versions might be expecting `npx @yext/pages init --folderToCreate pages-dec1`.

Let me know if that works for you! Additionally you should be able to interact with the CLI directly at `yext pages -h`

**Comment by vrunt** [comment]
Yext CLI Version: 0.1_305
@yext/pages@1.0.0-beta.6

`npx @yext/pages init --folderToCreate pages-dec1.` returns the same error.
I am able to use `yext pages new` to complete the process (though the CLI assumes a default branch name 'master' and not 'main', which caused some initial issues).
