### ISSUE TITLE
Image component doesn't work with Images from CFT

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#268]
### Describe the bug

We're trying to use the <Image> component with an image that comes from a CFT. 

You can see an example here: https://fidvcqhzez-42573-d.preview.pagescdn.com/sc/greenville/1125-woodruff-rd the images next to the services are not rendering. In the HTML we get something like this: 
```
<img style="object-fit:cover;object-position:center;width:100%;aspect-ratio:NaN / NaN" src="https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/500x500" srcset="https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/100xNaN 100w, https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/320xNaN 320w, https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/640xNaN 640w, https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/960xNaN 960w, https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/1280xNaN 1280w, https://dynl.mktgcdn.com/p/uLvItsXxb0eTHkhE2P5BewtVfeuq7e_wxx2vXSMjJZc/1920xNaN 1920w" sizes="(max-width: 640px) 100px, (max-width: 768px) 320px, (max-width: 1024px) 640px, (max-width: 1280px) 960px, (max-width: 1536px) 1280px, 1920px" loading="lazy" alt="ALL THINGS BROW">
```

The srcset urls have `NaN` in them instead of valid numbers. 

I think this is probably because images coming from cfts don't have `height` or `width` properties, they just have a `url`. 

Here's the entity for that page: https://www.yext.com/s/1934896/entity/edit3?entityIds=19920547 and the code that renders the images: https://github.com/yext-pages/Master-BenefitCosmetics/blob/PC-193526/trunk/src/components/entity/FeaturedProduct.tsx#L36

### Reproduction

https://fidvcqhzez-42573-d.preview.pagescdn.com/sc/greenville/1125-woodruff-rd

### System Info

```shell
n/a
```

### Used Package Manager

yarn

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Discussing with Product how the `Image` Component should behave when there is no height, width, or aspect ratio.

**Comment by tmeyer2115** [comment]
KG confirmed there is a bug on their side. This bug prevented images in `c_servicesList` from being assigned dimensions from PhotoServer. They indicated that we should expect all images to have dimensions. So, the Component is written properly. We're just discussing with Product if we should throw an error in the Component if no `imgWidth` or `imgHeight` is present.

**Comment by colton-demetriou** [comment]
https://github.com/yext/js/pull/14
