### ISSUE TITLE
entityIds stream filter option produces unexpected results

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#270]
### Describe the bug

I'm trying to use the `entityIds` option of the stream filter configuration, when serving my pages I get errors about multiple profiles being found that seem related to the stream not being filtered appropriately. 

For example:
* https://github.com/yextconsulting/site-starter-react-consulting/compare/pages-issue-270-repro?expand=1
* [Account - 3861963](https://www.yext.com/s/3861963/home)

When serving and trying to visit a url such as http://localhost:5173//ny/new-york/61-ninth-avenue I get an error about multiple  documents being found:
![image](https://user-images.githubusercontent.com/6308571/205377837-22532e56-4f66-4d07-ac13-a0b2f540b6da.png)

The logs in my terminal suggest that there's one document from the `locations` stream (expected) and one from `search-page`:
```
external id "[test-location]" found using slug value: "/ny/new-york/61-ninth-avenue".
Generated 0 files for stream "directory-root"
Generated 0 files for stream "directory-city"
Generated 1 files for stream "search-page"
Generated 0 files for stream "directory-region"
Generated 1 files for stream "locations"
```

The search-page stream is scoped to the single entity with id `search-page` so there shouldn't be a document from that stream. 

Changing my stream config from: `entityIds: ["search-page"],` to `savedFilterIds: ["1249026256"],` where [1249026256](https://www.yext.com/s/3861963/entities2#p0=entity%7Etext%7Elocation.store_id&p1=equal-to&p2=search-page&p3=&selectedSavedFilterId=231344) is a saved filter that contains the same single `search-page` entity avoids the error. 

### Reproduction

described above

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 266.40 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 107.0
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.13 => 1.0.0-beta.13
```

### Used Package Manager

npm

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Others have encountered this issue as well. It turns out that the `generate-test-data` command does not work properly when given an `--entityIds` flag. The `slug` behavior we added implicitly uses that flag. Spruce is working to correct the CLI command.

**Comment by mkilpatrick** [comment]
This has been fixed on Spruce's side.
