### ISSUE TITLE
npm run dev not running correctly for Windows User

### ISSUE THREAD

**Issue by lambdaFun94** [yext/pages#273]
### Describe the bug

While following the instructions in the Pages track, our devs found out that the command npm run dev  is not working properly on localhost:5173, since it does not load all the files. 

![image](https://user-images.githubusercontent.com/61638671/205949376-29382999-3060-4e57-b544-e3e4e122a643.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 4.91 GB / 15.89 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tmeyer2115** [comment]
Hi,

Thanks for bringing this issue to our attention! Could you please provide us with a repo and steps to reproduce? 

Thanks

**Comment by lambdaFun94** [comment]
Hello @tmeyer2115 - this is Andrew, proxying this request on from a client. User went through the Pages track in HH [here](https://hitchhikers.yext.com/tracks/pages-development/) and when running `npm run dev`, they received the above terminal output. The repo would be page starter react templates which is pulled directly during the HH onboarding flow.

**Comment by mkilpatrick** [comment]
Closing per Andrew
