### ISSUE TITLE
npm run dev - No Such File or Directory

### ISSUE THREAD

**Issue by dalygarrett** [yext/pages#283]
### Describe the bug

When attempting to run `npm run dev`, the following error message is returned:
` /bin/bash: C:\Users\rock_\rocktest002\node_modules\.bin\..\@yext\pages\dist\bin\pages.sh: No such file or directory`

We were able to successfully run this on Mac with no issues, however on both Windows 10 and Windows 11, we receive the error message. Both NPM and the Yext CLI are on the latest version (0.1_313).

### Reproduction

https://github.com/RocksGithub/rock01102023001

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Memory: 7.75 GB / 15.88 GB
Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
Managers:
    pip3: 22.3 - C:\Python311\Scripts\pip3.EXE
Utilities:
    Git: 2.39.0.
IDEs:
    VSCode: 1.74.3 - C:\Users\rock_\AppData\Local\Programs\Microsoft VS Code\bin\code.CMD
Languages:
    Bash: 5.1.4 - C:\Windows\system32\bash.EXE
    Python: 3.11.0
Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Used Browser

Edge

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by tatimblin** [comment]
Hello we received a [similar issue](https://github.com/yext/pages/issues/263#issuecomment-1341321397) for windows users. Can you try upgrading @yext/pages to beta version 14, it should fix your issue. If this persists at the version 14 let us know!

**Comment by tmeyer2115** [comment]
Based on [this](https://yext.slack.com/archives/C02UVSE7P6W/p1673296675042949) thread in Slack, it seems the customer has not updated their PagesJS version properly. Once they do update to 1.0.0-beta.15, this Windows issue should be fixed.
