### ISSUE TITLE
isProduction() util function not working as expected

### ISSUE THREAD

**Issue by lymarrie** [yext/pages#294]
### Describe the bug

Hello! I have a deployed site in production, and can still see a component I have rendering based on the isProduction util.

Here is my site link and example URL where the component is visible:
- https://sandbox.yext.com/s/3197999/yextsites/135022/branch/4870/deploys/recent (link to deploys page)
- https://cleverly-fair-louse.sbx.pgsdemo.com/location1-meatpacking (link to my web page URL)
- ^Notice the "Edit" button in the bottom-right side of the page

Here is the [code reference](https://github.com/yext/pages-starter-react-locations/blob/luc-module4/src/templates/location.tsx#L194) in my code.

### Reproduction

https://github.com/yext/pages-starter-react-locations/blob/luc-module4/src/templates/location.tsx#L194

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 153.08 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.9.0 - ~/.nvm/versions/node/v17.9.0/bin/node
    npm: 8.10.0 - ~/.nvm/versions/node/v17.9.0/bin/npm
  Browsers:
    Chrome: 110.0.5481.177
    Firefox: 100.0.2
    Safari: 15.2
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
The siteDomain is coming back as blank from the system which is causing the problem. It's not an issue with the function or PagesJS.
