### ISSUE TITLE
__INITIAL__DATA__ causes invalid HTML

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#370]
### Describe the bug

PagesJS injects the `__INITIAL__DATA__` window variable in a script tag at the top of the head. The content is often very large, which causes the `meta` tag that specified the charset for the page to be pushed down out of the first 1024 bytes of content, which is invalid according to the spec: https://www.w3.org/TR/2012/CR-html5-20121217/document-metadata.html#charset. 

This causes HTML validators such as https://validator.w3.org/nu/ to throw errors. Here's an example page that demonstrates this: https://browbars.benefitcosmetics.com/nv/las-vegas/2310-park-centre-dr.
![image](https://github.com/yext/pages/assets/6308571/bc0ba00e-79f9-41f7-b0fd-62bf4f1a8193)

Additionally, moving it below the CSS and JS scripts would allow those things to start loading more quickly. 

### Reproduction

https://browbars.benefitcosmetics.com/nv/las-vegas/2310-park-centre-dr

### System Info

```shell
n/a
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
We now don't use INITIAL_DATA and the script tag is the last one.
