### ISSUE TITLE
Use default vite.config.js when not provided

### ISSUE THREAD

**Issue by jwartofsky-yext** [yext/pages#382]
### Description

If a vite.config.js is not provided, Pages should use a default config.

### Suggested solution

Use a default config when vite.config.js is not present. The default config would be something like this:

```
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import yextSSG from "@yext/pages/vite-plugin";

export default defineConfig({
  plugins: [react(), yextSSG()],
});
```

### Additional context

https://github.com/yext/studio/pull/341/files#r1301902154

### Validations

- [X] Check that there isn't already an issue that requests the same feature to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
I don't think we should do this. A vite.config.js is a prerequisite of a Vite project. It's possible a user doesn't want to use the standard "@vitejs/plugin-react" plugin. They might want to use the legacy plugin. If they do that, then they might not include "@yext/pages/vite-plugin" and then nothing will work and could be confusing for a user.

The original reason this was opened was to make some test suites not require the vite.config.js, but I don't think following through with this issue just to make a test ever-so-slightly easier to set up is worth it at the expense of possible confusion for users.
