### ISSUE TITLE
Duplicate Stream Definitions in features.json

### ISSUE THREAD

**Issue by mancusi** [yext/pages#389]
### Describe the bug

When multiple templates define the same stream definition the generated features.json file contains all stream definitions.

For example if two templates have the following code then two stream definitions will appear in my `features.json` file twice:
```
import {
  TemplateConfig,
} from '../../SharedConfig

export const config = ConfigTemplateConfig;
```

I've attached a simple reproduction. It doesn't fully compile but it gives an example of how I'm sharing the stream configuration across templates.

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-vlh1h7?file=src%2Fshared.tsx

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 6.33 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
    pnpm: 7.5.2 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.5
  npmPackages:
    @yext/pages: 1.0.0-rc.2 => 1.0.0-rc.2
```

### Used Package Manager

pnpm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Fixed in https://github.com/yext/pages/pull/408
