### ISSUE TITLE
siteInternalHostName can't be used locally

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#390]
### Describe the bug

In repos configured for multiple domains sometimes we want to use the `siteInternalHostName` in order to customize pages depending on the active domain. 

This field doesn't get populated when serving locally, so it's not possible to test this logic before deploying.

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 451.96 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
    pnpm: 7.9.0 - ~/.nvm/versions/node/v17.4.0/bin/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Edge: 116.0.1938.81
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-beta.22 => 1.0.0-beta.22
```

### Used Package Manager

npm

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Fixed in https://github.com/yext/pages/pull/401
