### ISSUE TITLE
npm run dev fails while fetching sample documents

### ISSUE THREAD

**Issue by tanel7** [yext/pages#398]
### Describe the bug

Second step of https://hitchhikers.yext.com/tracks/pages-development/pgs601-build/03-create-site/ fails while running **npm run dev** with following error:

ERROR: Error fetching sample documents for stream city-stream
Failed binding the following fields to the schema: [c_addressRegionDisplayName, dm_directoryParents, dm_directoryChildren]
The document scope references the following object ids that are missing from the account: [ce_city]

### System Info

```shell
System:
    OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
    CPU: (1) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 2.73 GB / 3.82 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.8.0 - /usr/bin/node
    npm: 10.1.0 - /usr/bin/npm
  npmPackages:
    @yext/pages: 1.0.0-beta.21 => 1.0.0-beta.21
```

### Used Package Manager

npm

### Used Browser

Firefox

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
This isn't a PagesJS issue. Most likely some configuration wasn't applied properly to the account that the site is trying to use. If you ask for fields in your stream config of a template that don't exist in the account (or for that entityType), then pulling test data will fail.
