### ISSUE TITLE
Unable to use .otf fonts

### ISSUE THREAD

**Issue by bhainesva** [yext/pages#412]
### Describe the bug

I'm trying to use an .otf font in my project. Reproduction here: https://github.com/yextconsulting/pages-starter-react-consulting/tree/otf-fonts-repro, specific commit: https://github.com/yextconsulting/pages-starter-react-consulting/commit/0fb19cfd603e936d5fa8e139d2f4d6e2c2bd5ce6. 

When running pages commands I see errors like:
```
✘ [ERROR] Could not resolve "/src/assets/fonts/Connections_Light.otf"

    src/styles/fonts.css:3:11:
      3 │   src: url("/src/assets/fonts/Connections_Light.otf") format("truetype");
        ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/src/assets/fonts/Connections_Regular.otf"

    src/styles/fonts.css:11:11:
      11 │   src: url("/src/assets/fonts/Connections_Regular.otf") format("truetype");
         ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "/src/assets/fonts/Connections_Bold.otf"

    src/styles/fonts.css:19:11:
      19 │   src: url("/src/assets/fonts/Connections_Bold.otf") format("truetype");
         ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

For some commands (ex: `npx pages generate features`) these errors are fatal. For other like `npx pages dev` the command succeeds but the fonts don't work. 

### Reproduction

https://github.com/yextconsulting/pages-starter-react-consulting/commit/0fb19cfd603e936d5fa8e139d2f4d6e2c2bd5ce6

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.39 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nvm/versions/node/v17.4.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v17.4.0/bin/npm
    pnpm: 7.9.0 - ~/.nvm/versions/node/v17.4.0/bin/pnpm
  Browsers:
    Chrome: 118.0.5993.70
    Edge: 118.0.2088.46
    Safari: 15.4
  npmPackages:
    @yext/pages: 1.0.0-rc.5 => 1.0.0-rc.5
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Fixed in https://github.com/yext/pages/pull/416
