### ISSUE TITLE
Persistent "WebSocket server error: Port is already in use" Warning

### ISSUE THREAD

**Issue by lymarrie** [yext/pages#447]
### Describe the bug

I recently upgraded one of my repos to RC .4 and RC .6; on both, I see a persistent "WebSocket server error: Port is already in use" warning that doesn't go away. Despite the warning, my site works during local dev without issue, so I feel like the detection may be off.

Steps to replicate:
- git clone https://github.com/YextSolutions/fleet-smb-starter.git
- (cd into repo)
- git checkout upgrade
- npm run dev
- when prompted to init for the yextrc file, use 4060901 + prod

### Reproduction

https://github.com/YextSolutions/fleet-smb-starter

### System Info

```shell
Macbook pro Apple M1
node v 18.5.0
yext cli v 0.1_384
@yext/pages rc 4 onward
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
https://github.com/vitejs/vite/issues/14328
