### ISSUE TITLE
Not seeing full set of alternate language profiles in dev mode vs. prod mode

### ISSUE THREAD

**Issue by lymarrie** [yext/pages#466]
### Describe the bug

Seeing a discrepancy in the pages generated in dev vs prod mode, as it pertains to alternate language profiles. `Prod` mode seems correct; `dev` mode has issues.

Steps to replicate:
- Clone this [repo](https://github.com/lymarrie/multi-lang-repro)
- yext init 3248365 -u sandbox
- npm run dev
- As context, all-faqs.tsx generates a page for [this entity](https://sandbox.yext.com/s/3248365/entity/edit3?entityIds=92625609), which lists out several FAQs. This page is generated in both English and German. There are 6 entities total - 2 of which have _both_ English and German, the other 4 only having German. Therefore, when viewing the German version of the page, 6 FAQs should be visible, and when viewing English only 2 should be visible. In `dev` mode, only 2 FAQs are visible on both language pages. In `prod` mode, the correct FAQs are visible.

Dev Mode

<img width="1509" alt="local_dev" src="https://github.com/yext/pages/assets/16665882/593c6055-2880-480b-aa1d-2a9437c2e828">

Prod Mode

<img width="1511" alt="prod_dev" src="https://github.com/yext/pages/assets/16665882/b05b8088-da60-4c3d-b1e2-9e38eb4d546c">

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1013.95 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/.nvm/versions/node/v18.5.0/bin/node
    npm: 8.12.1 - ~/.nvm/versions/node/v18.5.0/bin/npm
    pnpm: 8.12.0 - ~/.nvm/versions/node/v18.5.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 15.2
  npmPackages:
    @yext/pages: 1.0.0-rc.7 => 1.0.0-rc.7
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
The command to generate-test-data is returning profiles where the slug doesn't match because it's the same entityId. We should fix that command to return what it's intended to return. As a workaround for now, you can append the locale to your prod url so it finds the right one: `http://localhost:5173/alle-faqs?locale=de`

**Comment by mkilpatrick** [comment]
This was fixed by CLI changes along with https://github.com/yext/pages/pull/498
