### ISSUE TITLE
unable to publish static pages with multiple locales

### ISSUE THREAD

**Issue by dgurland** [yext/pages#474]
### Describe the bug

When I try to publish a static page set with multiple locales, I get the publish error `Error: No localData files match entityId, featureName, and locale: , languageSelector, de` in the Build Generation. (languageSelector is the name of the page set)

### Reproduction

https://github.com/yext-pages/local.churchofjesuschrist.org/tree/dev/trunk

### System Info

```shell
System:
    OS: macOS 12.6.2
    CPU: (10) arm64 Apple M1 Max
    Memory: 24.46 GB / 64.00 GB
    Shell: 5.2.21 - /opt/homebrew/bin/bash
  Binaries:
    Node: 20.0.0 - ~/.nvm/versions/node/v20.0.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 9.6.3 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 120.0.6099.234
    Safari: 16.4.1
  npmPackages:
    @yext/pages: 1.0.0-rc.6 => 1.0.0-rc.6
```

### Used Package Manager

npm

### Used Browser

Chrome

### Validations

- [X] Check that there isn't [already an issue](https://github.com/yext/pages/issues) that reports the same bug to avoid creating a duplicate.

**Comment by mkilpatrick** [comment]
Fixed in https://github.com/yext/pages/pull/475
